/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Penjual;
import Model.Pembeli;
import Model.Product;
import Model.User;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haikal
 */
public class DashboardPembeli_Home extends javax.swing.JFrame {

    /**
     * Creates new form DashboardPenjual
     */
    public DashboardPembeli_Home(User u) {
        ArrayList<Product> arrProduct = new ArrayList<>();
        this.p = new Pembeli(u.getIdUser(), u.getNamaUser(), u.getEmail(), u.getPassword(), u.getRoles());
        ArrayList<Penjual> arrPenjual = this.p.getAllPenjual();
        for (Penjual pe : arrPenjual){
            ArrayList<Product> arrProductPenjual = pe.getAllProduct();
            for (Product prod : arrProductPenjual){
                arrProduct.add(prod);
            }
        }
        initComponents();
        DefaultTableModel tabModel = (DefaultTableModel)this.tabel_product_home.getModel();
        System.out.println(tabModel);
        for (Product product: arrProduct){
            Object[] data = {product.getIdProduct(), product.getNamaProduct(), product.getDeskripsi(), product.getHarga()};
            tabModel.addRow(data);
        }
        this.btn_addToCart.setEnabled(false);
    }
    
    public DashboardPembeli_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        navbar_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navbar_logout = new javax.swing.JPanel();
        label_logout = new javax.swing.JLabel();
        navbar_home = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        navbar_history = new javax.swing.JPanel();
        label_history = new javax.swing.JLabel();
        navbar_cart = new javax.swing.JPanel();
        label_cart = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_product_home = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_addToCart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar_panel.setBackground(new java.awt.Color(255, 255, 255));
        navbar_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Logo.png"))); // NOI18N
        navbar_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 50));

        navbar_logout.setBackground(new java.awt.Color(255, 255, 255));
        navbar_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbar_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navbar_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navbar_logoutMouseExited(evt);
            }
        });
        navbar_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_logout.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        label_logout.setText("Logout");
        navbar_logout.add(label_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 13, -1, -1));

        navbar_panel.add(navbar_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        navbar_home.setBackground(new java.awt.Color(255, 255, 255));
        navbar_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navbar_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navbar_homeMouseExited(evt);
            }
        });
        navbar_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        label_home.setForeground(new java.awt.Color(248, 11, 11));
        label_home.setText("Home");
        navbar_home.add(label_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 13, -1, -1));

        navbar_panel.add(navbar_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 50));

        navbar_history.setBackground(new java.awt.Color(255, 255, 255));
        navbar_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbar_historyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navbar_historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navbar_historyMouseExited(evt);
            }
        });
        navbar_history.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_history.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        label_history.setText("History");
        navbar_history.add(label_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 13, -1, -1));

        navbar_panel.add(navbar_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        navbar_cart.setBackground(new java.awt.Color(255, 255, 255));
        navbar_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbar_cartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navbar_cartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navbar_cartMouseExited(evt);
            }
        });
        navbar_cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_cart.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        label_cart.setText("Cart");
        navbar_cart.add(label_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 13, -1, -1));

        navbar_panel.add(navbar_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 50));

        main_panel.add(navbar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 620));

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_product_home.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tabel_product_home.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Product", "Nama Product", "Deskripsi", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_product_home.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_product_home.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tabel_product_home.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabel_product_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_product_homeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_product_home);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 700, 410));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel4.setText("List Barang ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btn_addToCart.setBackground(new java.awt.Color(255, 255, 255));
        btn_addToCart.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btn_addToCart.setText("Add to Cart");
        btn_addToCart.setFocusPainted(false);
        btn_addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addToCartActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 110, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 11, 11));
        jLabel5.setText("Home Pembeli");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        main_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 770, 620));

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 623));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navbar_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_logoutMouseEntered
        label_logout.setForeground(new Color(248, 11, 11));
        navbar_logout.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_navbar_logoutMouseEntered

    private void navbar_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_logoutMouseExited
        label_logout.setForeground(navbar_panel.getForeground());
        navbar_logout.setBackground(navbar_panel.getBackground());
    }//GEN-LAST:event_navbar_logoutMouseExited

    private void navbar_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_homeMouseEntered
       
    }//GEN-LAST:event_navbar_homeMouseEntered

    private void navbar_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_homeMouseExited
       
    }//GEN-LAST:event_navbar_homeMouseExited

    private void navbar_historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_historyMouseEntered
        label_history.setForeground(new Color(248, 11, 11));
        navbar_history.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_navbar_historyMouseEntered

    private void navbar_historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_historyMouseExited
        label_history.setForeground(navbar_panel.getForeground());
        navbar_history.setBackground(navbar_panel.getBackground());
    }//GEN-LAST:event_navbar_historyMouseExited

    private void navbar_cartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_cartMouseEntered
        label_cart.setForeground(new Color(248, 11, 11));
        navbar_cart.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_navbar_cartMouseEntered

    private void navbar_cartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_cartMouseExited
        label_cart.setForeground(navbar_panel.getForeground());
        navbar_cart.setBackground(navbar_panel.getBackground());
    }//GEN-LAST:event_navbar_cartMouseExited

    private void navbar_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_historyMouseClicked
       this.dispose();
       DashboardPembeli_History dashPembeliHistory = new DashboardPembeli_History(this.p);
       dashPembeliHistory.setVisible(true);
    }//GEN-LAST:event_navbar_historyMouseClicked

    private void btn_addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addToCartActionPerformed
        int selectedRow = this.tabel_product_home.getSelectedRow();
        Object id = this.tabel_product_home.getValueAt(selectedRow, 0);
        p.addToCart((int)id);
    }//GEN-LAST:event_btn_addToCartActionPerformed

    private void tabel_product_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_product_homeMouseClicked
        this.btn_addToCart.setEnabled(true);
    }//GEN-LAST:event_tabel_product_homeMouseClicked

    private void navbar_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_cartMouseClicked
        this.dispose();
        DashboardPembeli_Cart dashPembeliCart = new DashboardPembeli_Cart(this.p);
        dashPembeliCart.setVisible(true);
    }//GEN-LAST:event_navbar_cartMouseClicked

    private void navbar_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbar_logoutMouseClicked
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_navbar_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPembeli_Home().setVisible(true);
            }
        });
    }
    
    private Pembeli p;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addToCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cart;
    private javax.swing.JLabel label_history;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_logout;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel navbar_cart;
    private javax.swing.JPanel navbar_history;
    private javax.swing.JPanel navbar_home;
    private javax.swing.JPanel navbar_logout;
    private javax.swing.JPanel navbar_panel;
    private javax.swing.JTable tabel_product_home;
    // End of variables declaration//GEN-END:variables
}
